<a href="https://colab.research.google.com/github/VicDc/Uruz01/blob/main/7001_Problem%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt

#3D array
array_3d = np.array([
    [[ 0,  1,  2,  3],
     [ 4,  5,  6,  7],
     [ 8,  9, 10, 11],
     [12, 13, 14, 15]],

    [[16, 17, 18, 19],
     [20, 21, 22, 23],
     [24, 25, 26, 27],
     [28, 29, 30, 31]],

    [[32, 33, 34, 35],
     [36, 37, 38, 39],
     [40, 41, 42, 43],
     [44, 45, 46, 47]]
])

print("3D Array:")
print(array_3d)

# Extract diagonals from each 2D slice
diagonals = [np.diag(slice) for slice in array_3d]
diagonals = np.array(diagonals)

print("\nDiagonal Elements of Each 2D Slice:")
print(diagonals)

# Graph diagonal elements
for i, diag in enumerate(diagonals):
    plt.plot(range(len(diag)), diag, marker='o', label=f'Slice {i}')

plt.title("Diagonal Elements of Each 2D Slice")
plt.xlabel("Index")
plt.ylabel("Diagonal Value")
plt.legend()
plt.grid()
plt.show()


3D Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]

Diagonal Elements of Each 2D Slice:
[[ 0  5 10 15]
 [16 21 26 31]
 [32 37 42 47]]
